### ISSUE TITLE
TAB: using fancy-dabbrev-expand-or-indent breaks TAB on Magit

### ISSUE THREAD

**Issue by vindarel** [jrosdahl/fancy-dabbrev#11]
Hello,

you say:

```
;; If you want TAB to indent the line like it usually does when the cursor
;; is not next to an expandable word, use 'fancy-dabbrev-expand-or-indent
;; instead of `fancy-dabbrev-expand`:
(global-set-key (kbd "<tab>") 'fancy-dabbrev-expand-or-indent)
```

but it breaks TAB on a Magit buffer. There, TAB is bound to `magit-section-toggle`.

It probably breaks other modes.

I am not sure on the best fix.

Thanks for the package! cheers

**Comment by jrosdahl** [comment]
Hi there!

It doesn't break Magit for me at least (Emacs 27, Magit v3.1.1-15-g7f666751c022). Why do you think it does? Magit defines what TAB will do in its local keymaps, e.g. `magit-status-mode-map`, and they have priority over the global keymap.

**Comment by vindarel** [comment]
I think it does because I set the global key to expand or indent, TAB on magit doesn't work, for example to show a diff: suddenly I get 

> buffer is read only

:] I suppose TAB must tweaked only for fancy-dabbrev-mode. If it works for you, that's good news though^^

> hey have priority over the global keymap.

I didn't know that, but it doesn't seem to be the case with me, since `C-h k TAB` in a magit buffer to check shows it is bound to `fancy-dabbrev-expand-or-indent`.

Magit 20210105. I might need to update and see.

**Comment by jrosdahl** [comment]
Ah, now I understand. Emacs apparently performs translation between `TAB` and `<tab>` in a (to me) non-obvious way, and this interacts badly with Magit. See for example the comments to [this stackexchange answer](https://emacs.stackexchange.com/a/9634). And I of course use `TAB` instead of `<tab>` in my personal bindings, contrary to what I wrote as a hint in the README.

In other words, try this instead:

```elisp
(global-set-key (kbd "TAB") 'fancy-dabbrev-expand-or-indent)
```

**Comment by vindarel** [comment]
Perfect thank you!
