### ISSUE TITLE
Ability to preview and expand next word

### ISSUE THREAD

**Issue by elazdins** [jrosdahl/fancy-dabbrev#15]
Dabbrev supports expanding also after a space character. E.g. after having "detail " in my text and doing dabbrev-expand I get "detail oriented".

It appears fancy dabbrev does not support showing a preview and expanding also after a space character. So in my case after "detail " I would already see the preview for the next word "oriented".

Would it be possible to add this feature?

Thank you,

Edgars

**Comment by jrosdahl** [comment]
Thanks for the suggestion.

I first thought that it would be tricky to add such functionality, but after having a look it turned out to actually be very easy unless I'm missing some edge case.

To try it out, all you have to do is to evaluate

```elisp
(defun fancy-dabbrev--looking-back-at-expandable () t)
```

after loading `fancy-dabbrev.el`. Could you do that and report back if it behaves like you imagined? If so, I can add a setting to make this behavior opt-in.

**Comment by elazdins** [comment]
Just tried it and it works exactly as expected! Look forward to you adding this as an opt-in setting :)

**Comment by jrosdahl** [comment]
There were indeed some edge cases I needed to fix, but hopefully done now. Just load the latest version of fancy-dabbrev and configure it like this:

```elisp
(setq fancy-dabbrev-expansion-context 'after-symbol-or-space)
```
