### ISSUE TITLE
Making sure case matches the sentence

### ISSUE THREAD

**Issue by elazdins** [jrosdahl/fancy-dabbrev#16]
Hi,

Not sure if this is a fancy-dabbrev or dabbrev issue, but what is the best way to make sure the expanded word matches expected case?

For example, when I write "we need to l", fancy-dabbrev suggests to expand the last character to "look", which is great, but when I complete the word it comes out as "we need to Look". Is there a setting to match the already started case (so L expands to Look and l expands to look) or make sure the expansion is always lowercase?

Thank you and apologies if this is already covered by documentation. I reviewed the existing configuration settings and could not really find one that fits the bill.

Edgars

**Comment by jrosdahl** [comment]
It's fancy-dabbrev that doesn't imitate dabbrev-expand when dabbrev-case-replace is t. I haven't really considered that case since I'm using fancy-dabbrev for case-sensitive programming symbols and then it doesn't make much sense to replace case. But I think I've found out how to make it work for a true dabbrev-case-replace!
